# Generated by Django 5.1.5 on 2025-01-28 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenado', models.CharField(max_length=200)),
                ('enderecoEnvio', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subTotal', models.PositiveIntegerField()),
                ('desconto', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('pedidoStatus', models.CharField(choices=[('Pedido Recebido ', 'Pedido Recebido'), ('Pedido Processando ', 'Pedido Processando'), ('Pedido Caminho ', 'Pedido Caminho'), ('Pedido Concluido ', 'Pedido Concluido'), ('Pedido Cancelado ', 'Pedido Cancelado')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrinho.carrinho')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
